site_name: Injectify Documentation

# Repository
repo_name: 'samdenty99/injectify'
repo_url: 'https://github.com/samdenty99/injectify'

# Copyright
copyright: 'Copyright &copy; 2018 Sam Denty'

# Configuration
theme:
  name: 'material'
  logo: 'assets/images/logo.svg'
  favicon: 'assets/images/favicon.ico'
  feature:
    tabs: true

# Pages
pages:
  - Introduction: 'index.md'
  - Getting Started:
    - Installation:
      - Creating a MongoDB database: 'getting-started/installation/mongodb.md'
      - Creating a GitHub application: 'getting-started/installation/github.md'
      - Configuration: 'getting-started/installation/configuration.md'

# Extensions
markdown_extensions:
  - toc:
      permalink: true
  - meta
  - footnotes
  - codehilite
  - admonition
  - pymdownx.details
  - pymdownx.emoji
  - pymdownx.smartsymbols

# Resources
extra_javascript:
  - 'assets/js/crate.js'
extra_css:
  - 'assets/css/main.css'

# Analytics
google_analytics:
  - 'UA-85426772-6'
  - 'auto'

# Footer links
extra:
  social:
    - type: 'github'
      link: 'https://github.com/samdenty99'
    - type: 'twitter'
      link: 'https://twitter.com/thesamdd'