site_name: Injectify Documentation

# Repository
repo_name: 'samdenty99/injectify'
repo_url: 'https://github.com/samdenty99/injectify'

# Copyright
copyright: 'Copyright &copy; 2018 Sam Denty'

# Configuration
theme:
  name: 'material'
  logo: 'images/logo.svg'
  favicon: 'images/favicon.ico'
  feature:
    tabs: true

# Resources
extra_javascript:
  - 'js/crate.js'

# Analytics
google_analytics:
  - 'UA-85426772-6'
  - 'auto'

# Footer links
extra:
  social:
    - type: 'github'
      link: 'https://github.com/samdenty99'
    - type: 'twitter'
      link: 'https://twitter.com/thesamdd'