site_name: Injectify Documentation

# Repository
repo_name: 'samdenty99/injectify'
repo_url: 'https://github.com/samdenty99/injectify'
edit_uri: 'https://github.com/injectify/docs/edit/master/docs/'

# Meta
site_description: 'Perform advanced MiTM attacks on websites with ease.'
site_author: 'samdd'
copyright: 'Copyright &copy; 2018 Sam Denty'

# Configuration
theme:
  name: 'material'
  logo: 'assets/images/logo.svg'
  favicon: 'assets/images/favicon.ico'
  feature:
    tabs: true

# Pages
pages:
  - Introduction: 'index.md'
  - Getting Started:
    - Installation:
      - Creating a MongoDB database: 'getting-started/installation/mongodb.md'
      - Creating a GitHub application: 'getting-started/installation/github.md'
      - Configuration: 'getting-started/installation/configuration.md'
      - Setting up the server: 'getting-started/installation/setting-up.md'
    - Using it:
      - Generating JS payloads: 'usage/payload-generator.md'
      - Hooking browsers: 'usage/inject.md'
      - Password extractor: 'usage/passwords.md'
      - Keylogger: 'usage/keylogger.md'
      - Project configuration:
        - Managing users & roles: 'usage/project-config/roles.md'
        - Managing domain filters: 'usage/project-config/filters.md'
        - Project API: 'usage/project-config/api.md'
  - Usage:
    - Generating JS payloads: 'usage/payload-generator.md'
    - Hooking browsers: 'usage/inject.md'
    - Password extractor: 'usage/passwords.md'
    - Keylogger: 'usage/keylogger.md'
    - Project configuration:
      - Managing users & roles: 'usage/project-config/roles.md'
      - Managing domain filters: 'usage/project-config/filters.md'
      - Project API: 'usage/project-config/api.md'
  - Inject:
    - Modules:
      - Creating a module: 'inject/modules/create.md'
      - Module API: 'inject/modules/api.md'
  - Demos:
      - Interface demos: 'demos/interface.md'

  # Extensions
markdown_extensions:
  - toc:
      permalink: true
  - meta
  - footnotes
  - codehilite
  - admonition
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
# Resources
extra_javascript:
  - 'assets/js/crate.js'
extra_css:
  - 'assets/css/main.css'

# Analytics
google_analytics:
  - 'UA-85426772-6'
  - 'auto'

# Footer links
extra:
  social:
    - type: 'github'
      link: 'https://github.com/samdenty99'
    - type: 'twitter'
      link: 'https://twitter.com/thesamdd'